### ISSUE TITLE
CSD compatibility and Status Quo

### ISSUE THREAD

**Issue by IBA4** [talisein/mal-gtk#8]
First of all, it was so good to find one for Linux (though late). @talisein  are you still working on it? It would be so nice to see some Client Side Decoration here. It will look updated and you know what I mean.
 If you are planning to do this or think that you should abandon it, do you have any plans or any suggestions for what others should do if they plan on doing a similar thing?

**Comment by talisein** [comment]
I am still working on this project, but I get slowed down from playing games. I have a rather large in-progress commit locally that fixes #3 for example, but I haven't made time to finish the automated testing to keep it from being broken for too long again. Since few people use this project I do not feel too much pressure to go fast :)

I'm not sure exactly what you mean by client side decoration. Using the latest Gtk+ library means CSD is being used. But if you mean defining my own compact HeaderBar, I guess that would be a part of my plans for a 'UI Refresh' in the github projects tab.

If you or anyone have a specific request please feel free to bring it up. And If you are so motivated to help for the UI, mocking something up using Glade. And if you are super motivated, write a [glade catalog](https://developer.gnome.org/gladeui/stable/catalogintro.html) for libmalgtk

**Comment by IBA4** [comment]
Oh! I didn't quite look into project tabs. This definitely was in mind then.
https://github.com/Drutol/MALClient can be some sort of inspiration. I don't know if we can make mal-gtk par with that. But we can definitely give it a try.

**Comment by IBA4** [comment]
@talisein Should I close this issue?
